DATA:
  datadir : ../Dataset/MVtecAD
  dataset : MVtecAD
  imgcls : pill
  imgsize : 256 
  mode : full 

TRAIN:
  batchsize : 8
  device : cuda
  lr : 0.005
  epochs : 50
  seed : 111
  scheulder : false
  multigpu : true 

SAVE:
  savedir : './save_models'
  wandb : true

MODEL:
  encoder : wide_resnet50_2 
  decoder : de_wide_resnet50_2