DATA:
  datadir : ../Dataset/MVtecAD
  dataset : MvtecAD
  imgcls : bottle
  imgsize : 256 
  mode : full 

TRAIN:
  batchsize : 16
  device : cuda
  lr : 0.001
  epochs : 100 
  seed : 111

SAVE:
  savedir : './save_models'