DATA:
  datadir : ../Dataset/MVtecAD
  dataset : MVtecAD
  imgcls : screw
  imgsize : 256 
  mode : full 

TRAIN:
  batchsize : 8
  device : cuda
  lr : 0.001
  epochs : 100 
  seed : 111

SAVE:
  savedir : './save_models'

MODEL:
  encoder : resnet34 
  decoder : de_resnet34