DATA:
  datadir : ../Dataset/MVtecAD
  dataset : MVtecAD
  imgcls : grid
  imgsize : 256 
  mode : full 

TRAIN:
  batchsize : 8
  device : cuda
  lr : 0.001
  epochs : 10
  seed : 111

SAVE:
  savedir : './save_models'
  wandb : false 

MODEL:
  encoder : wide_resnet50_2 
  decoder : de_wide_resnet50_2