DATA:
  datadir: ../Dataset/ViSA
  dataset: ViSA
  imgcls: capsules
  imgsize: 1024
  mode: full
MODEL:
  decoder: de_wide_resnet50_2
  encoder: wide_resnet50_2
SAVE:
  savedir: ./save_models/Large
  wandb: true
TRAIN:
  batchsize: 1
  device: cuda
  epochs: 100
  lr: 0.005
  multigpu: true
  scheulder: false
  seed: 111
