DATA:
  datadir : ../Dataset/ViSA
  dataset : ViSA
  imgcls : pcb2
  imgsize : 256 
  mode : full 

TRAIN:
  batchsize : 16
  device : cuda:1
  lr : 0.001
  epochs : 100 
  seed : 111

SAVE:
  savedir : './save_models'